augmentation_job:
  approach: "SEQ" #"PAR"
  export: True
  paths:
    import_path:
    export_path:

augmentation_approach:
  sequential:
    sequence:
#      - time_stretch
      - pitch_shift
#      - volume_control
#      - add_noise
#      - time_shift
#      - bandpass_filter
#      - add_reverb
#      - polarity_inversion
  parallel:
    methods:
      - time_stretch
      - pitch_shift
      - volume_control
      - add_noise
      - time_shift
      - bandpass_filter
      - add_reverb
      - polarity_inversion
    n_methods: 8

augmentation_method:
  time_stretch:
    p: 0
    rate: [0.8, 1.2]
  pitch_shift:
    p: 1
    sr: 22050
    bins_per_octave: 12
    n_steps: [-2, 2]
  volume_control:
    p: 0
    gain_dB: [-3, 3]
  add_noise:
    p: 0
    snr_db: [15, 20]
  time_shift:
    p: 0
    shift_pct: [-1, 1]
  lowpass_filter:
    p: 0
    lowcut: 4000
  highpass_filter:
    p: 0
    highcut: 300
  bandpass_filter:
    p: 0
    lowcut: 300
    highcut: 4000
    filter_order: 5
    sr: 22050
  add_reverb:
    p: 0
    sr: 22050
    delay: 0
    rt60: 0.4
    room_dim: [6, 6, 3]
    src_pos: [3, 3, 1.5]
    mic_pos: [3, 2.6, 1.5]
  polarity_inversion:
    p: 0

file_suffixes:
  generate_suffixes: True
  detailed_suffixes: False
  time_stretch:
    suffix: "_TST"
  pitch_shift:
    suffix: "_aug2"
  volume_control:
    suffix: "_VC"
  add_noise:
    suffix: "_AN"
  time_shift:
    suffix: "_TSH"
  lowpass_filter:
    suffix: "_LPF"
  highpass_filter:
    suffix: "_HPF"
  bandpass_filter:
    suffix: "_BPF"
  add_reverb:
    suffix: "_RVR"
  polarity_inversion:
    suffix: "_PI"
